.\" Man Page for ukui-window-switch
.TH UKUI-WINDOW-SWITCH 1 "December 23, 2017" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
\fBukui-window-switch\fR \- Front of the window switcher in UKUI desktop environment
.SH "SYNOPSIS"
.B ukui-window-switch
.SH "DESCRIPTION"
Front of the window switcher in UKUI desktop environment.
Provides the display function(Display window thumbnails and application icons) when the window is switching (press Alt+Tab key).
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui/ukui-window-switch/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
Droiing <jianglinxuan@kylinos.cn> (2017)
