#############################################################################
# Makefile for building: ukui-window-switch
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  ukui-window-switch.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ukui-window-switch.pro 'QMAKE_CFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CXXFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CXXFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' 'QMAKE_LFLAGS_DEBUG=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' QMAKE_STRIP=: PREFIX=/usr
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -pthread -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/libwnck-3.0 -isystem /usr/include/startup-notification-1.0 -isystem /usr/include/gtk-3.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/fribidi -isystem /usr/include/harfbuzz -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -isystem /usr/include/aarch64-linux-gnu/qt5/QGSettings -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/KF5/KGlobalAccel -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/KF5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ukui-window-switch1.0.0
DISTDIR = /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/.tmp/ukui-window-switch1.0.0
LINK          = g++
LFLAGS        = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,-rpath-link,/usr/lib/aarch64-linux-gnu
LIBS          = $(SUBLIBS) -lX11 -lwnck-3 -lgtk-3 -latk-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lgsettings-qt /usr/lib/aarch64-linux-gnu/libQt5X11Extras.so /usr/lib/aarch64-linux-gnu/libKF5GlobalAccel.so /usr/lib/aarch64-linux-gnu/libQt5Widgets.so /usr/lib/aarch64-linux-gnu/libQt5Gui.so /usr/lib/aarch64-linux-gnu/libQt5DBus.so /usr/lib/aarch64-linux-gnu/libKF5WaylandClient.so /usr/lib/aarch64-linux-gnu/libKF5WaylandServer.so /usr/lib/aarch64-linux-gnu/libQt5Core.so /usr/lib/aarch64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = :

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/ukws_indicator.cpp \
		src/ukws_new_workspace_button.cpp \
		src/ukws_stack_blur.cpp \
		src/ukws_wayland_handler.cpp \
		src/ukws_wnck_operator.cpp \
		src/ukws_helper.cpp \
		src/ukws_window_box.cpp \
		src/ukws_window_extra_label.cpp \
		src/ukws_flowlayout.cpp \
		src/ukws_config.cpp \
		src/ukws_dbus.cpp \
		src/ukws_workspace_manager.cpp \
		src/ukws_workspace_box.cpp \
		src/ukws_manager.cpp \
		src/ukws_worker.cpp \
		src/ukws_fake_desktop.cpp \
		src/ukws_window_info.cpp \
		src/ukws_workspace_multiview.cpp moc_ukws_indicator.cpp \
		moc_ukws_new_workspace_button.cpp \
		moc_ukws_stack_blur.cpp \
		moc_ukws_window_box.cpp \
		moc_ukws_window_extra_label.cpp \
		moc_ukws_config.cpp \
		moc_ukws_dbus.cpp \
		moc_ukws_workspace_manager.cpp \
		moc_ukws_workspace_box.cpp \
		moc_ukws_manager.cpp \
		moc_ukws_worker.cpp \
		moc_ukws_fake_desktop.cpp \
		moc_ukws_window_info.cpp \
		moc_ukws_workspace_multiview.cpp
OBJECTS       = main.o \
		ukws_indicator.o \
		ukws_new_workspace_button.o \
		ukws_stack_blur.o \
		ukws_wayland_handler.o \
		ukws_wnck_operator.o \
		ukws_helper.o \
		ukws_window_box.o \
		ukws_window_extra_label.o \
		ukws_flowlayout.o \
		ukws_config.o \
		ukws_dbus.o \
		ukws_workspace_manager.o \
		ukws_workspace_box.o \
		ukws_manager.o \
		ukws_worker.o \
		ukws_fake_desktop.o \
		ukws_window_info.o \
		ukws_workspace_multiview.o \
		moc_ukws_indicator.o \
		moc_ukws_new_workspace_button.o \
		moc_ukws_stack_blur.o \
		moc_ukws_window_box.o \
		moc_ukws_window_extra_label.o \
		moc_ukws_config.o \
		moc_ukws_dbus.o \
		moc_ukws_workspace_manager.o \
		moc_ukws_workspace_box.o \
		moc_ukws_manager.o \
		moc_ukws_worker.o \
		moc_ukws_fake_desktop.o \
		moc_ukws_window_info.o \
		moc_ukws_workspace_multiview.o
DIST          = data/default-background.jpg \
		data/org.ukui.WindowSwitch.service \
		data/ukui-window-switch.conf \
		theme/default.qss \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ukui-window-switch.pro src/ukws_indicator.h \
		src/ukws_new_workspace_button.h \
		src/ukws_stack_blur.h \
		src/ukws_wayland_handler.h \
		src/ukws_wnck_operator.h \
		src/ukws_helper.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_flowlayout.h \
		src/ukws_config.h \
		src/ukws_common.h \
		src/ukws_dbus.h \
		src/ukws_workspace_manager.h \
		src/ukws_workspace_box.h \
		src/ukws_manager.h \
		src/ukws_worker.h \
		src/ukws_fake_desktop.h \
		src/ukws_window_info.h \
		src/ukws_workspace_multiview.h src/main.cpp \
		src/ukws_indicator.cpp \
		src/ukws_new_workspace_button.cpp \
		src/ukws_stack_blur.cpp \
		src/ukws_wayland_handler.cpp \
		src/ukws_wnck_operator.cpp \
		src/ukws_helper.cpp \
		src/ukws_window_box.cpp \
		src/ukws_window_extra_label.cpp \
		src/ukws_flowlayout.cpp \
		src/ukws_config.cpp \
		src/ukws_dbus.cpp \
		src/ukws_workspace_manager.cpp \
		src/ukws_workspace_box.cpp \
		src/ukws_manager.cpp \
		src/ukws_worker.cpp \
		src/ukws_fake_desktop.cpp \
		src/ukws_window_info.cpp \
		src/ukws_workspace_multiview.cpp
QMAKE_TARGET  = ukui-window-switch
DESTDIR       = 
TARGET        = ukui-window-switch


first: all
####### Build rules

ukui-window-switch:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ukui-window-switch.pro /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ukui-window-switch.pro
	$(QMAKE) -o Makefile ukui-window-switch.pro 'QMAKE_CFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CXXFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CXXFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' 'QMAKE_LFLAGS_DEBUG=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' QMAKE_STRIP=: PREFIX=/usr
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
ukui-window-switch.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ukui-window-switch.pro 'QMAKE_CFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CXXFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_CXXFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' 'QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' 'QMAKE_LFLAGS_DEBUG=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' QMAKE_STRIP=: PREFIX=/usr

qmake_all: FORCE


all: Makefile ukui-window-switch

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/ukws_indicator.h src/ukws_new_workspace_button.h src/ukws_stack_blur.h src/ukws_wayland_handler.h src/ukws_wnck_operator.h src/ukws_helper.h src/ukws_window_box.h src/ukws_window_extra_label.h src/ukws_flowlayout.h src/ukws_config.h src/ukws_common.h src/ukws_dbus.h src/ukws_workspace_manager.h src/ukws_workspace_box.h src/ukws_manager.h src/ukws_worker.h src/ukws_fake_desktop.h src/ukws_window_info.h src/ukws_workspace_multiview.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/ukws_indicator.cpp src/ukws_new_workspace_button.cpp src/ukws_stack_blur.cpp src/ukws_wayland_handler.cpp src/ukws_wnck_operator.cpp src/ukws_helper.cpp src/ukws_window_box.cpp src/ukws_window_extra_label.cpp src/ukws_flowlayout.cpp src/ukws_config.cpp src/ukws_dbus.cpp src/ukws_workspace_manager.cpp src/ukws_workspace_box.cpp src/ukws_manager.cpp src/ukws_worker.cpp src/ukws_fake_desktop.cpp src/ukws_window_info.cpp src/ukws_workspace_multiview.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -O2 -fdebug-prefix-map=/home/ky/ukui-window-switch/ukui-window-switch-3.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -pthread -pthread -Wall -W -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_ukws_indicator.cpp moc_ukws_new_workspace_button.cpp moc_ukws_stack_blur.cpp moc_ukws_window_box.cpp moc_ukws_window_extra_label.cpp moc_ukws_config.cpp moc_ukws_dbus.cpp moc_ukws_workspace_manager.cpp moc_ukws_workspace_box.cpp moc_ukws_manager.cpp moc_ukws_worker.cpp moc_ukws_fake_desktop.cpp moc_ukws_window_info.cpp moc_ukws_workspace_multiview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ukws_indicator.cpp moc_ukws_new_workspace_button.cpp moc_ukws_stack_blur.cpp moc_ukws_window_box.cpp moc_ukws_window_extra_label.cpp moc_ukws_config.cpp moc_ukws_dbus.cpp moc_ukws_workspace_manager.cpp moc_ukws_workspace_box.cpp moc_ukws_manager.cpp moc_ukws_worker.cpp moc_ukws_fake_desktop.cpp moc_ukws_window_info.cpp moc_ukws_workspace_multiview.cpp
moc_ukws_indicator.cpp: src/ukws_indicator.h \
		src/ukws_common.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_flowlayout.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_indicator.h -o moc_ukws_indicator.cpp

moc_ukws_new_workspace_button.cpp: src/ukws_new_workspace_button.h \
		src/ukws_window_extra_label.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_new_workspace_button.h -o moc_ukws_new_workspace_button.cpp

moc_ukws_stack_blur.cpp: src/ukws_stack_blur.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_stack_blur.h -o moc_ukws_stack_blur.cpp

moc_ukws_window_box.cpp: src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_window_box.h -o moc_ukws_window_box.cpp

moc_ukws_window_extra_label.cpp: src/ukws_window_extra_label.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_window_extra_label.h -o moc_ukws_window_extra_label.cpp

moc_ukws_config.cpp: src/ukws_config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_config.h -o moc_ukws_config.cpp

moc_ukws_dbus.cpp: src/ukws_dbus.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_dbus.h -o moc_ukws_dbus.cpp

moc_ukws_workspace_manager.cpp: src/ukws_workspace_manager.h \
		src/ukws_indicator.h \
		src/ukws_common.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_flowlayout.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h \
		src/ukws_workspace_box.h \
		src/ukws_new_workspace_button.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_workspace_manager.h -o moc_ukws_workspace_manager.cpp

moc_ukws_workspace_box.cpp: src/ukws_workspace_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wnck_operator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_workspace_box.h -o moc_ukws_workspace_box.cpp

moc_ukws_manager.cpp: src/ukws_manager.h \
		src/ukws_common.h \
		src/ukws_indicator.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_flowlayout.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h \
		src/ukws_workspace_manager.h \
		src/ukws_workspace_box.h \
		src/ukws_new_workspace_button.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_manager.h -o moc_ukws_manager.cpp

moc_ukws_worker.cpp: src/ukws_worker.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_window_info.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_worker.h -o moc_ukws_worker.cpp

moc_ukws_fake_desktop.cpp: src/ukws_fake_desktop.h \
		src/ukws_common.h \
		src/ukws_window_info.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wayland_handler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_fake_desktop.h -o moc_ukws_fake_desktop.cpp

moc_ukws_window_info.cpp: src/ukws_window_info.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_window_info.h -o moc_ukws_window_info.cpp

moc_ukws_workspace_multiview.cpp: src/ukws_workspace_multiview.h \
		src/ukws_fake_desktop.h \
		src/ukws_common.h \
		src/ukws_window_info.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wayland_handler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ky/ukui-window-switch/ukui-window-switch-3.0.0 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KGlobalAccel -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtDBus -I/usr/include/KF5 -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/ukws_workspace_multiview.h -o moc_ukws_workspace_multiview.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/ukws_wnck_operator.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_indicator.h \
		src/ukws_common.h \
		src/ukws_flowlayout.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h \
		src/ukws_workspace_manager.h \
		src/ukws_workspace_box.h \
		src/ukws_new_workspace_button.h \
		src/ukws_helper.h \
		src/ukws_dbus.h \
		src/ukws_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

ukws_indicator.o: src/ukws_indicator.cpp src/ukws_indicator.h \
		src/ukws_common.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_flowlayout.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_indicator.o src/ukws_indicator.cpp

ukws_new_workspace_button.o: src/ukws_new_workspace_button.cpp src/ukws_common.h \
		src/ukws_new_workspace_button.h \
		src/ukws_window_extra_label.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_new_workspace_button.o src/ukws_new_workspace_button.cpp

ukws_stack_blur.o: src/ukws_stack_blur.cpp src/ukws_stack_blur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_stack_blur.o src/ukws_stack_blur.cpp

ukws_wayland_handler.o: src/ukws_wayland_handler.cpp src/ukws_wayland_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_wayland_handler.o src/ukws_wayland_handler.cpp

ukws_wnck_operator.o: src/ukws_wnck_operator.cpp src/ukws_wnck_operator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_wnck_operator.o src/ukws_wnck_operator.cpp

ukws_helper.o: src/ukws_helper.cpp src/ukws_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_helper.o src/ukws_helper.cpp

ukws_window_box.o: src/ukws_window_box.cpp src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_common.h \
		src/ukws_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_window_box.o src/ukws_window_box.cpp

ukws_window_extra_label.o: src/ukws_window_extra_label.cpp src/ukws_window_extra_label.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_window_extra_label.o src/ukws_window_extra_label.cpp

ukws_flowlayout.o: src/ukws_flowlayout.cpp src/ukws_flowlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_flowlayout.o src/ukws_flowlayout.cpp

ukws_config.o: src/ukws_config.cpp src/ukws_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_config.o src/ukws_config.cpp

ukws_dbus.o: src/ukws_dbus.cpp src/ukws_dbus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_dbus.o src/ukws_dbus.cpp

ukws_workspace_manager.o: src/ukws_workspace_manager.cpp src/ukws_common.h \
		src/ukws_workspace_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wnck_operator.h \
		src/ukws_workspace_manager.h \
		src/ukws_indicator.h \
		src/ukws_window_box.h \
		src/ukws_flowlayout.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h \
		src/ukws_new_workspace_button.h \
		src/ukws_stack_blur.h \
		src/ukws_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_workspace_manager.o src/ukws_workspace_manager.cpp

ukws_workspace_box.o: src/ukws_workspace_box.cpp src/ukws_workspace_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wnck_operator.h \
		src/ukws_common.h \
		src/ukws_window_box.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_workspace_box.o src/ukws_workspace_box.cpp

ukws_manager.o: src/ukws_manager.cpp src/ukws_manager.h \
		src/ukws_common.h \
		src/ukws_indicator.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_flowlayout.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_info.h \
		src/ukws_wayland_handler.h \
		src/ukws_workspace_manager.h \
		src/ukws_workspace_box.h \
		src/ukws_new_workspace_button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_manager.o src/ukws_manager.cpp

ukws_worker.o: src/ukws_worker.cpp src/ukws_worker.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_window_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_worker.o src/ukws_worker.cpp

ukws_fake_desktop.o: src/ukws_fake_desktop.cpp src/ukws_fake_desktop.h \
		src/ukws_common.h \
		src/ukws_window_info.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wayland_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_fake_desktop.o src/ukws_fake_desktop.cpp

ukws_window_info.o: src/ukws_window_info.cpp src/ukws_window_info.h \
		src/ukws_common.h \
		src/ukws_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_window_info.o src/ukws_window_info.cpp

ukws_workspace_multiview.o: src/ukws_workspace_multiview.cpp src/ukws_workspace_multiview.h \
		src/ukws_fake_desktop.h \
		src/ukws_common.h \
		src/ukws_window_info.h \
		src/ukws_wnck_operator.h \
		src/ukws_config.h \
		src/ukws_worker.h \
		src/ukws_window_box.h \
		src/ukws_window_extra_label.h \
		src/ukws_wayland_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukws_workspace_multiview.o src/ukws_workspace_multiview.cpp

moc_ukws_indicator.o: moc_ukws_indicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_indicator.o moc_ukws_indicator.cpp

moc_ukws_new_workspace_button.o: moc_ukws_new_workspace_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_new_workspace_button.o moc_ukws_new_workspace_button.cpp

moc_ukws_stack_blur.o: moc_ukws_stack_blur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_stack_blur.o moc_ukws_stack_blur.cpp

moc_ukws_window_box.o: moc_ukws_window_box.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_window_box.o moc_ukws_window_box.cpp

moc_ukws_window_extra_label.o: moc_ukws_window_extra_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_window_extra_label.o moc_ukws_window_extra_label.cpp

moc_ukws_config.o: moc_ukws_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_config.o moc_ukws_config.cpp

moc_ukws_dbus.o: moc_ukws_dbus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_dbus.o moc_ukws_dbus.cpp

moc_ukws_workspace_manager.o: moc_ukws_workspace_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_workspace_manager.o moc_ukws_workspace_manager.cpp

moc_ukws_workspace_box.o: moc_ukws_workspace_box.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_workspace_box.o moc_ukws_workspace_box.cpp

moc_ukws_manager.o: moc_ukws_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_manager.o moc_ukws_manager.cpp

moc_ukws_worker.o: moc_ukws_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_worker.o moc_ukws_worker.cpp

moc_ukws_fake_desktop.o: moc_ukws_fake_desktop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_fake_desktop.o moc_ukws_fake_desktop.cpp

moc_ukws_window_info.o: moc_ukws_window_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_window_info.o moc_ukws_window_info.cpp

moc_ukws_workspace_multiview.o: moc_ukws_workspace_multiview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukws_workspace_multiview.o moc_ukws_workspace_multiview.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin/ || mkdir -p $(INSTALL_ROOT)/usr/bin/
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_services: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/dbus-1/services/ || mkdir -p $(INSTALL_ROOT)/usr/share/dbus-1/services/
	-$(QINSTALL) /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/data/org.ukui.WindowSwitch.service $(INSTALL_ROOT)/usr/share/dbus-1/services/org.ukui.WindowSwitch.service

uninstall_services: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dbus-1/services/org.ukui.WindowSwitch.service
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 


install_theme: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/ukui-window-switch/theme/ || mkdir -p $(INSTALL_ROOT)/usr/share/ukui-window-switch/theme/
	-$(QINSTALL) /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/theme/default.qss $(INSTALL_ROOT)/usr/share/ukui-window-switch/theme/default.qss

uninstall_theme: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/ukui-window-switch/theme/default.qss
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ukui-window-switch/theme/ 


install_conf: first FORCE
	@test -d $(INSTALL_ROOT)/etc/ukui/ukui-window-switch/ || mkdir -p $(INSTALL_ROOT)/etc/ukui/ukui-window-switch/
	-$(QINSTALL) /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/data/ukui-window-switch.conf $(INSTALL_ROOT)/etc/ukui/ukui-window-switch/ukui-window-switch.conf

uninstall_conf: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/etc/ukui/ukui-window-switch/ukui-window-switch.conf
	-$(DEL_DIR) $(INSTALL_ROOT)/etc/ukui/ukui-window-switch/ 


install_background: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/ukui-window-switch/data/ || mkdir -p $(INSTALL_ROOT)/usr/share/ukui-window-switch/data/
	-$(QINSTALL) /home/ky/ukui-window-switch/ukui-window-switch-3.0.0/data/default-background.jpg $(INSTALL_ROOT)/usr/share/ukui-window-switch/data/default-background.jpg

uninstall_background: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/ukui-window-switch/data/default-background.jpg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ukui-window-switch/data/ 


install: install_target install_services install_theme install_conf install_background  FORCE

uninstall: uninstall_target uninstall_services uninstall_theme uninstall_conf uninstall_background  FORCE

FORCE:

